export const Actions = {
  CHANGE_DATE_RANGE: `CHANGE_DATE_RANGE`,
  DELETE_ARTICLE: `DELETE_ARTICLE`,
  ADD_COMMENT: `ADD_COMMENT`,
  LOAD_ALL_ARTICLES: `LOAD_ALL_ARTICLES`,
  LOAD_ARTICLE: `LOAD_ARTICLE`,
  LOAD_COMMENTS: `LOAD_COMMENTS`,
  LOAD_COMMENTS_FOR_PAGE: `LOAD_COMMENTS_FOR_PAGE`
}

export const Status = {
  START: `_START`,
  SUCCESS: `_SUCCESS`,
  FAIL: `_FAIL`,
}

export const API = {
  ARTICLES: `/api/article`,
  ARTICLE: `/api/article/`
}